/*FUNCIONES PARA EL CANAL 4 DE CONVERSION A/D DEL SISTEMA BOLT 18F2550
DEBE CONECTARSE AL PUERTO AUXILIAR UNA TARJETA DE INTERFAZ Ó UN SENSOR
PARA GENERAR EL VOLTAJE ANALOGICO DE 0 A 5 VOLTS, EL CUAL INGRESA A TRAVÉS
DEL PIN 2 DEL PUERTO AUXILIAR. ENTRADA CANAL 4 (RA5) DEL 18F2550. 
INCLUYA LA LIBRERIA <adc.h> EN EL PROGRAMA PRINCIPAL*/

/*FUNCIONES DISPONIBLES*/

void open_bolt_adc(void);
int bolt_adc(void);

void open_bolt_adc(void)		//FUNCION INICIALIZA ADC, CANAL 4
{
OpenADC( ADC_FOSC_64 &
ADC_RIGHT_JUST &
ADC_12_TAD,
ADC_CH4 &
ADC_INT_OFF,15);
}

int bolt_adc(void)		//FUNCION REGRESA CON RESULTADO DE CONVERSION Y DESACTIVA EL ADC
{
int a;
ADCON1=10;				//ACTIVA CANAL 4
ConvertADC(); 			// Inicia conversion
while( BusyADC() ); 	// Espera fin de conversión
a = ReadADC(); 			// lee resultado
ADCON1=15;				//DESACTIVA CANAL 4
return a;
}
